package studentr

func (r *studentRepoDB) GetStudentProfile(studentCode string) (student *StudentProfileRepo, err error) {
	student_info := StudentProfileRepo{}
	query := `SELECT 
		SS.ENROLL_YEAR,SS.ENROLL_SEMESTER ,SS.STD_CODE, 
		SS.PRENAME_THAI_S, SS.PRENAME_ENG_S, SS.FIRST_NAME,SS.LAST_NAME, 
		SS.FIRST_NAME_ENG, SS.LAST_NAME_ENG, SS.THAI_NAME, SS.PLAN_NO,
		SS.SEX, SS.REGINAL_NAME, SS.SUBSIDY_NAME,
		SS.STATUS_NAME_THAI, SS.BIRTH_DATE, SS.STD_ADDR, SS.ADDR_TEL, SS.JOB_POSITION,
		SS.STD_OFFICE, SS.OFFICE_TEL,SS.DEGREE_NAME,
		SS.BSC_DEGREE_NO, SS.BSC_DEGREE_THAI_NAME, SS.BSC_INSTITUTE_NO,
		SS.INSTITUTE_THAI_NAME, SS.CK_CERT_NO, SS.CHK_CERT_NAME_THAI,
		C.ENG_NAME
		FROM DBGMIS00.VM_STUDENT S 
		LEFT JOIN DBGMIS00.VM_STUDENT_S SS ON S.STD_CODE = SS.STD_CODE 
		LEFT JOIN DBGMIS00.VM_CURRICULUM C ON S.MAJOR_NO = C.MAJOR_NO AND S.CURR_NO = C.CURR_NO 
		WHERE SS.STD_CODE = :PARAM1`

	err = r.oracle_db.Get(&student_info, query, studentCode)
	if err != nil {
		return nil, err
	}

	student = &student_info

	return student, nil
}
