version: '3.5'
services:
  ru-connext-caching:   
    image: redis:6.0
    container_name:  ru-connext-caching
    restart: always    
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data
      - ./redis_config/redis.conf:/redis.conf
    command: redis-server /redis.conf --requirepass  admin-ru-connext-caching --appendonly yes

  ru-connext-api:
    image:  ruconnext-api
    container_name:  ru-connext-api
    restart: always
    depends_on:
      -  ru-connext-caching
    ports:
      - 8883:8883

  ru-smart-api:   
    #build: ./
    image: ru-smart-api
    container_name: ru-smart-api
    restart: always  
    depends_on:
      - ru-connext-caching  
    ports:
      - 9100:8883
    volumes:
      - ./:/app
    command: reflex -r "\.go$$" -s -- sh -c "go run ./"
    #command: go run main.go

networks:
  default:
    external: 
      name: backend-services
